apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: registry-pull-rolebinding
  namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:image-puller
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:clouds-api-dev
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:clouds-api-qa
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:clouds-api-prod    