apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: clouds-api
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: 'ArgoCD Project dedicated for clouds-api application'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
