apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pipelines-clusterrole
rules:
- apiGroups:
  - argoproj.io
  resources:
  - appprojects
  - applications
  verbs:
  - patch
  - get
  - create
  