apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-secret-reader-rb
  namespace: clouds-build
subjects:
- kind: ServiceAccount
  name: pipeline # Replace 'pipeline' if your PipelineRuns use a different SA
  namespace: clouds-build
roleRef:
  kind: Role
  name: secret-reader-for-pipeline
  apiGroup: rbac.authorization.k8s.io
