apiVersion: v1
kind: Secret
metadata:
  name: quay-robot-creds
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJxdWF5LmlvIjogewogICAgICAiYXV0aCI6ICJjMkZoTFd4aGRHRnRLM05oWVd4aGRHRnRPbGhOT1RCS1JUUkVOMEpOU2pRMFVWYzBVbFJETlZKRFRrTTROMWd4VWpsR05sbzRTa1F3VURaVFFWUkJSMGMwVHpJNVJWRkxVVVl4TkZBME1VZzNXVEU9IiwKICAgICAgImVtYWlsIjogIiIKICAgIH0KICB9Cn0=
type: kubernetes.io/dockerconfigjson
