apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-clouds-api-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: clouds-api
  - name: git-url
    value: https://github.com/pecorawal/ocp-pipelines.git
  - name: IMAGE
<<<<<<< HEAD
<<<<<<< HEAD
    value: image-registry.openshift-image-registry.svc:5000/app1-dev/clouds-api
=======
    value: image-registry.openshift-image-registry.svc:5000/pipeline1/clouds-api
>>>>>>> 01234e5 (pipeline1)
=======
    value: image-registry.openshift-image-registry.svc:5000/clouds-api/clouds-api
>>>>>>> 17e4cf3 (fix imagestream)
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
