apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-deploy-clouds-api-pipelinerun
spec:
  pipelineRef:
    name: build-and-deploy
  params:
  - name: deployment-name
    value: clouds-api
  - name: git-url
    value: https://github.com/pecorawal/ocp-pipelines.git
  - name: IMAGE
    value: image-registry.openshift-image-registry.svc:5000/clouds-api/clouds-api
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
