apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-to-quay
  namespace: clouds-build
spec:
  workspaces:
    - name: shared-workspace
    - name: dockerconfig        
  params:
    - name: image
    - name: commit 
  results:
    - name: image-tag
  steps:
    - name: build-and-push
      image: quay.io/podman/stable
      securityContext:
        privileged: true 
      env:
        - name: "HOME"
          value: "/tmp"          
      script: |-
        export REGISTRY_AUTH_FILE=$(workspaces.dockerconfig.path)/config.json
        build_date=`date +'%Y%m%d%H%M%S'`          
        short=`echo $(params.commit) | cut -c 1-7`
        cd $(workspaces.output.path)
        podman build . -t $(params.image):$short.$build_date
        podman push $(params.image):$short.$build_date 
        podman push $(params.image):$short.$build_date $(params.image):latest
        echo "$short.$build_date" > $(results.image-tag.path)
